apiVersion: v2
name: spire-crds
description: >
  A Helm chart for deploying the Spire CRDS
type: application
version: 0.5.0-cofide.1
appVersion: "0.0.1"
keywords: ["spire-crds"]
home: https://github.com/cofide/spiffe-helm-charts-hardened/tree/main/charts/spire-crds
sources:
  - https://github.com/cofide/spiffe-helm-charts-hardened/tree/main/charts/spire-crds
icon: https://spiffe.io/img/logos/spire/icon/color/spire-icon-color.png
maintainers:
  - name: Cofide
    url: https://cofide.io
